from yacs.config import CfgNode as CN

_C = CN()

_C.MODEL = CN()
_C.MODEL.NAME = "groundingdino"
_C.MODEL.WEIGHT = ""

_C.MODEL.BACKBONE = CN()
_C.MODEL.BACKBONE.NAME = "swin_T_224_1k"
_C.MODEL.BACKBONE.OUT_CHANNELS = [96, 192, 384, 768]
_C.MODEL.BACKBONE.DILATION = False

_C.MODEL.NECK = CN()
_C.MODEL.NECK.NAME = "MultiScaleDeformableAttention"
_C.MODEL.NECK.IN_CHANNELS = [96, 192, 384, 768]
_C.MODEL.NECK.OUT_CHANNEL = 256
_C.MODEL.NECK.NUM_LAYERS = 6
_C.MODEL.NECK.NUM_HEADS = 8

_C.MODEL.DECODER = CN()
_C.MODEL.DECODER.NAME = "GroundingDINOTransformerDecoder"
_C.MODEL.DECODER.NUM_LAYERS = 6
_C.MODEL.DECODER.NUM_HEADS = 8
_C.MODEL.DECODER.DIM_FEEDFORWARD = 2048

_C.MODEL.TEXT_ENCODER = CN()
_C.MODEL.TEXT_ENCODER.NAME = "bert-base-uncased"
_C.MODEL.TEXT_ENCODER.DIM = 768

_C.MODEL.MULTI_MODAL = CN()
_C.MODEL.MULTI_MODAL.ENABLED = True
_C.MODEL.MULTI_MODAL.MODALITIES = ["rgb", "ir", "depth"]
_C.MODEL.MULTI_MODAL.INPUT_CHANNELS_RGB = 3
_C.MODEL.MULTI_MODAL.INPUT_CHANNELS_IR = 1
_C.MODEL.MULTI_MODAL.INPUT_CHANNELS_DEPTH = 1
_C.MODEL.MULTI_MODAL.ADAPTER_DIM = 96
_C.MODEL.MULTI_MODAL.USE_GATED_FUSION = True
_C.MODEL.MULTI_MODAL.USE_TEXT_GUIDANCE = True

_C.MODEL.USE_SWIN = True
_C.MODEL.PRETRAINED = True
_C.MODEL.MAX_SEQ_LEN = 256

_C.MODEL.MASK_ON = False
_C.MODEL.NUM_QUERIES = 900
_C.MODEL.HIDDEN_DIM = 256

_C.SOLVER = CN()
_C.SOLVER.BASE_LR = 1e-4
_C.SOLVER.WEIGHT_DECAY = 1e-4
_C.SOLVER.EPOCHS = 50
_C.SOLVER.BATCH_SIZE = 8
_C.SOLVER.WARMUP_EPOCHS = 5
_C.SOLVER.LR_DROP_EPOCHS = [40]
_C.SOLVER.GRADIENT_ACCUMULATION_STEPS = 1
_C.SOLVER.AMP = False
_C.SOLVER.NUM_WORKERS = 0

_C.DATASETS = CN()
_C.DATASETS.TRAIN = []
_C.DATASETS.TEST = []
_C.DATASETS.DATA_PATH = "./data"
_C.DATASETS.MAX_TRAIN_SAMPLES = -1
_C.DATASETS.MAX_VAL_SAMPLES = -1

_C.INPUT = CN()
_C.INPUT.SIZE_TRAIN = (512, 512)
_C.INPUT.SIZE_TEST = (512, 512)

_C.OUTPUT_DIR = "./output"
_C.LOG_DIR = "./logs"

_C.TEST = CN()
_C.TEST.EVAL_PERIOD = 5
_C.TEST.SAVE_BEST_ONLY = True
_C.TEST.EARLY_STOPPING_PATIENCE = 15

_C.DISTRIBUTED = CN()
_C.DISTRIBUTED.ENABLED = False
_C.DISTRIBUTED.WORLD_SIZE = 1
_C.DISTRIBUTED.RANK = 0

_C.LOCAL_RANK = -1
_C.MASTER_ADDR = "127.0.0.1"
_C.MASTER_PORT = "29500"

_C.DTYPE = "float32"


def get_cfg():
    return _C.clone()
