from groundingdino.config.defaults import _C as cfg

cfg.MODEL.NAME = "groundingdino_multi_modal"

cfg.MODEL.BACKBONE.NAME = "swin_T_224_1k"
cfg.MODEL.BACKBONE.OUT_CHANNELS = [96, 192, 384, 768]

cfg.MODEL.NECK.NAME = "MultiScaleDeformableAttention"
cfg.MODEL.NECK.IN_CHANNELS = [96, 192, 384, 768]
cfg.MODEL.NECK.OUT_CHANNEL = 256
cfg.MODEL.NECK.NUM_LAYERS = 6
cfg.MODEL.NECK.NUM_HEADS = 8

cfg.MODEL.DECODER.NAME = "GroundingDINOTransformerDecoder"
cfg.MODEL.DECODER.NUM_LAYERS = 6
cfg.MODEL.DECODER.NUM_HEADS = 8
cfg.MODEL.DECODER.DIM_FEEDFORWARD = 2048

cfg.MODEL.TEXT_ENCODER.NAME = "bert-base-uncased"
cfg.MODEL.TEXT_ENCODER.DIM = 768

cfg.MODEL.MULTI_MODAL.ENABLED = True
cfg.MODEL.MULTI_MODAL.MODALITIES = ["rgb", "ir", "depth"]
cfg.MODEL.MULTI_MODAL.INPUT_CHANNELS_RGB = 3
cfg.MODEL.MULTI_MODAL.INPUT_CHANNELS_IR = 1
cfg.MODEL.MULTI_MODAL.INPUT_CHANNELS_DEPTH = 1
cfg.MODEL.MULTI_MODAL.ADAPTER_DIM = 96
cfg.MODEL.MULTI_MODAL.USE_GATED_FUSION = True
cfg.MODEL.MULTI_MODAL.USE_TEXT_GUIDANCE = True

cfg.MODEL.MASK_ON = False
cfg.MODEL.NUM_QUERIES = 100
cfg.MODEL.HIDDEN_DIM = 128

cfg.SOLVER.BASE_LR = 5e-5
cfg.SOLVER.WEIGHT_DECAY = 1e-4
cfg.SOLVER.EPOCHS = 60
cfg.SOLVER.BATCH_SIZE = 2
cfg.SOLVER.GRADIENT_ACCUMULATION_STEPS = 2
cfg.SOLVER.WARMUP_EPOCHS = 3
cfg.SOLVER.AMP = False
cfg.SOLVER.NUM_WORKERS = 0

cfg.DATASETS.TRAIN = ["multi_modal_train"]
cfg.DATASETS.TEST = ["multi_modal_val"]
cfg.DATASETS.DATA_PATH = "./data"
cfg.DATASETS.MAX_TRAIN_SAMPLES = 320
cfg.DATASETS.MAX_VAL_SAMPLES = 80

cfg.INPUT.SIZE_TRAIN = (512, 512)
cfg.INPUT.SIZE_TEST = (512, 512)

cfg.OUTPUT_DIR = "./output"
cfg.LOG_DIR = "./logs"

cfg.TEST.EVAL_PERIOD = 5
cfg.TEST.SAVE_BEST_ONLY = True
cfg.TEST.EARLY_STOPPING_PATIENCE = 20

def get_cfg():
    return cfg.clone()